name: Smilecare Public Website Production Deployment Workflow

on:
  push:
    branches:
      - master

env:
  CI: true
  REACT_APP_LINK: ${{ secrets.REACT_APP_LINK }}
  INLINE_RUNTIME_CHUNK: false

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm i
      - run: npm run build
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          args: deploy --dir=build --prod
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "smilecare-public"
          heroku_email: ${{ secrets.EMAIL }}
